name: CICIDS Automation Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y curl git unzip wget python3-pip docker.io docker-compose tcpreplay mongodb-org snort suricata zeek
      - name: Set Up Python Virtual Environment
        run: |
          python3 -m venv cicids_env
          source cicids_env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          deactivate

  deploy-metabase:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Deploy Metabase
        run: |
          source cicids_env/bin/activate
          chmod +x scripts/deploy_metabase.sh
          ./scripts/deploy_metabase.sh
          deactivate

  deploy-dash:
    runs-on: ubuntu-latest
    needs: deploy-metabase
    steps:
      - name: Deploy Dash Web Application
        run: |
          source cicids_env/bin/activate
          python3 scripts/deploy_dash.py
          deactivate

